[uwsgi]
chdir = /var/www/gqeg564/app

home = /var/www/gqeg564/.venv

module = core.wsgi:application

master = true
processes = 4
threads = 2

socket = /var/www/gqeg564/project.sock
chmod-socket = 666
vacuum = true

die-on-term = true